# Generated by Django 3.1.5 on 2021-01-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayhunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scavenges',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='scavenges',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='scavenges',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='scavenges',
            name='Points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
