# Generated by Django 3.1.5 on 2021-01-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayhunt', '0002_auto_20210111_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scavenges',
            options={'verbose_name_plural': 'scavenges'},
        ),
    ]
