# Generated by Django 3.1.5 on 2021-01-15 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthdayhunt', '0003_auto_20210113_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='complete_scavenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(default='Lier-vs.-Liar.jpg', upload_to='proof_pics')),
                ('huntId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthdayhunt.scavenges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
