# Generated by Django 3.1.5 on 2021-01-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayhunt', '0004_complete_scavenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_scavenges',
            name='proof',
            field=models.ImageField(default='Lier-vs.-Liar.jpg', upload_to='proof_pics/'),
        ),
    ]
