# Generated by Django 3.1.5 on 2021-01-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayhunt', '0005_auto_20210115_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complete_scavenges',
            options={'verbose_name_plural': 'complete scavenges'},
        ),
    ]
