# Generated by Django 3.1.5 on 2021-01-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayhunt', '0006_auto_20210115_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_scavenges',
            name='finish_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
