# Generated by Django 3.1.5 on 2021-01-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_huntcompleteion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='huntcompleteion',
            field=models.DateTimeField(blank=True),
        ),
    ]
