# Generated by Django 3.1.5 on 2021-01-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_scavenge_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scavenge_start',
        ),
    ]
