# Generated by Django 3.1.5 on 2021-01-19 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_scavenge_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
