# Generated by Django 3.1.5 on 2021-01-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starttime',
        ),
    ]
