# Generated by Django 3.1.5 on 2021-01-19 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 18, 22, 54, 43, 403453)),
            preserve_default=False,
        ),
    ]
