# Generated by Django 3.1.5 on 2021-01-19 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 23, 4, 12, 295355)),
        ),
    ]
