# Generated by Django 3.1.5 on 2021-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
